# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-16 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyllabusExamType',
            fields=[
                ('syll_exmType_id', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('create_user', models.CharField(blank=True, max_length=20, null=True)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('update_user', models.CharField(blank=True, max_length=20, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'syllabus_examType',
                'managed': False,
            },
        ),
    ]
